# Generated by Django 4.2.7 on 2024-01-29 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='cast-pic')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Cinsiyet')),
                ('birth', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('cast_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castapp.cast_role', verbose_name='Görev')),
            ],
        ),
    ]
