# Generated by Django 4.2.7 on 2024-02-12 11:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='full_name'),
        ),
    ]
