# Generated by Django 4.2.7 on 2024-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_customuser_city_alter_customuser_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile-photo'),
        ),
    ]
