# Generated by Django 4.2.7 on 2024-02-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_customuser_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile-photo'),
        ),
    ]
