# Generated by Django 4.2.7 on 2024-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_remove_movie_actor_movie_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='image',
            field=models.ImageField(default=1, upload_to='cast-pic'),
            preserve_default=False,
        ),
    ]
