# Generated by Django 4.2.7 on 2024-01-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_cast_role_remove_cast_is_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='cast_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movieapp.cast_role'),
            preserve_default=False,
        ),
    ]
