# Generated by Django 4.2.7 on 2024-01-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_cast_cast_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
