# Generated by Django 4.2.7 on 2024-01-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0010_movie_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmler'},
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='title',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='cast',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
