# Generated by Django 4.2.7 on 2024-01-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0011_alter_movie_options_rename_title_cast_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='movie-pic'),
            preserve_default=False,
        ),
    ]
