# Generated by Django 4.2.7 on 2024-01-25 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0012_movie_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.cast_role', verbose_name='Görev'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
