# Generated by Django 4.2.7 on 2024-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0014_remove_movie_video_movie_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url_first', models.CharField(blank=True, max_length=200)),
                ('url_second', models.CharField(blank=True, max_length=200)),
                ('url_third', models.CharField(blank=True, max_length=200)),
                ('url_fourth', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.ManyToManyField(to='movieapp.video'),
        ),
    ]
