# Generated by Django 4.2.7 on 2024-01-29 14:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0015_video_remove_movie_video_url_movie_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.ManyToManyField(blank=True, to='movieapp.video'),
        ),
    ]
