# Generated by Django 4.2.7 on 2024-01-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castapp', '0001_initial'),
        ('movieapp', '0016_category_slug_alter_movie_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='castapp.cast'),
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='Cast_Role',
        ),
    ]
